/* GENERATED by tools/gen_audio.py */
#ifndef AUDIO_DATA_H
#define AUDIO_DATA_H
#include "gba.h"
#define NOTE_COUNT 84
#define TRACK_COUNT 4
#define TRACK_MENU 0
#define TRACK_GAME 1
#define TRACK_INTENSE 2
#define TRACK_GAMEOVER 3
extern const u16 note_square[NOTE_COUNT + 1];
extern const u16 note_wave[NOTE_COUNT + 1];
extern const u32 wave_table[4];
extern const u16 track_step_x256[TRACK_COUNT];
extern const u8 track_loop[TRACK_COUNT];
extern const u8 track_lead[TRACK_COUNT][64];
extern const u8 track_bass[TRACK_COUNT][64];
extern const u8 track_drums[TRACK_COUNT][64];
#endif
