#!/usr/bin/env python3
"""gen_audio.py - compiles the original NIGHTFALL music patterns into data/audio_data.c

The GBA's PSG has two square channels, a 32-sample wave channel and a noise channel.
Music is a step sequencer: every track is 64 sixteenth-note steps long per channel.

Pattern notation (one string per bar of 16 steps):
    NOTE[:len]   e.g. E2:2   note E in octave 2 lasting 2 steps
    -[:len]      rest
Drum bars are written as 16 characters:  K kick, S snare, h closed hat, o open hat,
t tom, . nothing.

Output: note frequency register tables, the wave-channel waveform, tempo table and
all tracks.  Run from the repo root:  python3 tools/gen_audio.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

NOTE_NAMES = {'C': 0, 'C#': 1, 'D': 2, 'D#': 3, 'E': 4, 'F': 5, 'F#': 6, 'G': 7, 'G#': 8, 'A': 9, 'A#': 10, 'B': 11}
LOWEST_OCT = 1          # table index 1 == C1
NOTES = 12 * 7          # C1 .. B7


def midi_hz(n):
    return 440.0 * 2 ** ((n - 69) / 12.0)


def note_index(name):
    """'E2' -> 1-based table index (C1 = 1); 0 is reserved for 'rest'"""
    if len(name) >= 3 and name[1] == '#':
        n, o = name[:2], int(name[2:])
    else:
        n, o = name[0], int(name[1:])
    return (o - LOWEST_OCT) * 12 + NOTE_NAMES[n] + 1


def parse_bar(bar, steps=16):
    out = []
    bar = bar.replace(' :', ':')
    for tok in bar.split():
        length = 1
        if ':' in tok:
            tok, l = tok.split(':')
            length = int(l)
        if tok == '-':
            out += [0] * length
        else:
            out += [note_index(tok)] + [255] * (length - 1)
    assert len(out) == steps, (bar, len(out))
    return out


def parse_drums(bar):
    m = {'.': 0, 'K': 1, 'S': 2, 'h': 3, 'o': 4, 't': 5}
    assert len(bar) == 16, bar
    return [m[c] for c in bar]


TRACKS = {}


def track(name, bpm, lead, bass, drums, loop=True):
    TRACKS[name] = dict(bpm=bpm, lead=sum((parse_bar(b) for b in lead), []),
                        bass=sum((parse_bar(b) for b in bass), []),
                        drums=sum((parse_drums(b) for b in drums), []), loop=loop)
    for k in ('lead', 'bass', 'drums'):
        assert len(TRACKS[name][k]) == 64, (name, k, len(TRACKS[name][k]))


# ---- MENU: slow, cold, ambient ------------------------------------------------
track('MENU', 76,
      lead=["- :4 E4:2 - :2 B4:2 - :2 G4:2 - :2",
            "- :2 E5:2 - :2 D5:2 B4:4 - :4",
            "- :4 C5:2 - :2 G4:2 - :2 E4:2 - :2",
            "- :2 B3:2 - :2 D4:2 E4:6 - :2"],
      bass=["E1:16", "E1:8 F1:8", "C1:8 D1:4 E1:4", "B1:8 E1:8"],
      drums=["K...............", "K.......h.......", "K...............", "K.......h...h..."])

# ---- GAME: tense, mechanical, E phrygian --------------------------------------
track('GAME', 104,
      lead=["- :8 E4:4 F4:4",
            "G4:8 - :4 F4:4",
            "E4:6 - :2 D4:4 E4:4",
            "- :8 B3:4 C4:4"],
      bass=["E1:2 E1:2 E1:2 E2:2 E1:2 E1:2 G1:2 E1:2",
            "E1:2 E1:2 E1:2 E2:2 E1:2 E1:2 B1:2 A1:2",
            "C2:2 C2:2 C2:2 C3:2 C2:2 C2:2 D2:2 C2:2",
            "D2:2 D2:2 D2:2 D3:2 D2:2 D2:2 F2:2 E2:2"],
      drums=["K.h.S.h.K.h.S.hh", "K.h.S.h.K.hKS.h.", "K.h.S.h.K.h.S.hh", "K.hKS.h.K.h.S.ho"])

# ---- INTENSE: fast, driving ---------------------------------------------------
track('INTENSE', 148,
      lead=["E4:2 E5:2 B4:2 E5:2 G4:2 E5:2 F4:2 E5:2",
            "E4:2 E5:2 B4:2 E5:2 A4:2 E5:2 G4:2 B4:2",
            "C5:2 G4:2 E5:2 G4:2 D5:2 A4:2 F5:2 A4:2",
            "B4:2 F4:2 D5:2 F4:2 E5:4 B4:2 C5:2"],
      bass=["E1 E1 E2 E1 E1 E2 E1 G1 E1 E1 E2 E1 E1 F1 G1 F1",
            "E1 E1 E2 E1 E1 E2 E1 B1 E1 E1 E2 E1 A1 G1 F1 E1",
            "C2 C2 C3 C2 C2 C3 C2 D2 C2 C2 C3 C2 C2 D2 E2 D2",
            "B1 B1 B2 B1 B1 B2 B1 D2 B1 B1 B2 B1 C2 B1 A1 B1"],
      drums=["K.hKS.hKK.hKS.hS", "K.hKS.hKK.hKS.SS", "K.hKS.hKK.hKS.hS", "KhhKSh.KKhhKSSSS"])

# ---- GAME OVER: slow collapse (plays once) ------------------------------------
track('GAMEOVER', 66,
      lead=["E4:8 D4:8", "C4:8 B3:8", "A3:16", "E3:16"],
      bass=["E1:16", "C1:16", "A1:16", "E1:16"],
      drums=["K...............", "........K.......", "................", "................"],
      loop=False)


def build():
    lines = ['/* GENERATED by tools/gen_audio.py - original NIGHTFALL music data. Do not edit. */',
             '#include "gba.h"', '#include "audio_data.h"', '']
    # note tables: square channel and wave channel register values (11 bit)
    sq = [0]
    wv = [0]
    for i in range(NOTES):
        hz = midi_hz(24 + i)          # C1 = MIDI 24
        xs = int(round(2048 - 131072.0 / hz))
        xw = int(round(2048 - 65536.0 / hz))
        sq.append(max(0, min(2047, xs)) if xs > 0 else 0)
        wv.append(max(0, min(2047, xw)))
    lines.append('const u16 note_square[NOTE_COUNT + 1] = {' + ','.join(str(v) for v in sq) + '};')
    lines.append('const u16 note_wave[NOTE_COUNT + 1] = {' + ','.join(str(v) for v in wv) + '};')
    # wave channel waveform: a soft sawtooth / triangle mix (32 x 4 bit)
    wave = []
    for i in range(32):
        t = i / 32.0
        tri = 2 * t if t < 0.5 else 2 - 2 * t
        wave.append(max(0, min(15, int(round((0.55 * tri + 0.45 * t) * 15)))))
    words = []
    for i in range(0, 32, 8):
        b = []
        for j in range(4):                     # each byte holds two samples, high nibble first
            b.append((wave[i + j * 2] << 4) | wave[i + j * 2 + 1])
        words.append(b[0] | (b[1] << 8) | (b[2] << 16) | (b[3] << 24))
    lines.append('const u32 wave_table[4] = {' + ','.join('0x%08X' % w for w in words) + '};')
    names = list(TRACKS.keys())
    lines.append('const u16 track_step_x256[%d] = {%s};' % (
        len(names), ','.join(str(int(round(900.0 * 256 / t['bpm']))) for t in TRACKS.values())))
    lines.append('const u8 track_loop[%d] = {%s};' % (len(names), ','.join('1' if t['loop'] else '0' for t in TRACKS.values())))
    for kind in ('lead', 'bass', 'drums'):
        lines.append('const u8 track_%s[%d][64] = {' % (kind, len(names)))
        for t in TRACKS.values():
            lines.append('    {' + ','.join(str(v) for v in t[kind]) + '},')
        lines.append('};')
    open(os.path.join(ROOT, 'data', 'audio_data.c'), 'w').write('\n'.join(lines) + '\n')
    with open(os.path.join(ROOT, 'data', 'audio_data.h'), 'w') as f:
        f.write('/* GENERATED by tools/gen_audio.py */\n#ifndef AUDIO_DATA_H\n#define AUDIO_DATA_H\n#include "gba.h"\n')
        f.write('#define NOTE_COUNT %d\n#define TRACK_COUNT %d\n' % (NOTES, len(names)))
        for i, n in enumerate(names):
            f.write('#define TRACK_%s %d\n' % (n, i))
        f.write('extern const u16 note_square[NOTE_COUNT + 1];\nextern const u16 note_wave[NOTE_COUNT + 1];\n')
        f.write('extern const u32 wave_table[4];\nextern const u16 track_step_x256[TRACK_COUNT];\nextern const u8 track_loop[TRACK_COUNT];\n')
        f.write('extern const u8 track_lead[TRACK_COUNT][64];\nextern const u8 track_bass[TRACK_COUNT][64];\nextern const u8 track_drums[TRACK_COUNT][64];\n#endif\n')
    print('gen_audio: %d tracks, %d notes' % (len(names), NOTES))


if __name__ == '__main__':
    build()
