#!/usr/bin/env python3
"""png2gba.py - converts the indexed PNG sheets in assets/ into GBA 4bpp tile data.

Reads  assets/manifest.json  (written by gen_assets.py) and the PNG sheets, writes
    data/gfx_data.c   palettes + tile data (const arrays)
    data/gfx_ids.h    tile offsets / sprite frame offsets used by the C code

PNG conventions
  * every sheet is an *indexed* PNG whose palette has 256 entries = 16 banks x 16
  * pixel value v  ->  palette bank = v >> 4, 4bpp colour slot = v & 15
  * slot 0 is transparent
BG sheets are cut into 8x8 tiles, OBJ sheets into frames (frame_w x frame_h) which
are stored in 1D-mapping order (row-major tiles inside a frame).
Edit the PNGs (any indexed-PNG editor) and run `python3 tools/png2gba.py` to rebuild.
"""
import json
import os
import sys
from PIL import Image


def load(root, rel):
    im = Image.open(os.path.join(root, rel))
    assert im.mode == 'P', rel + ' must be an indexed PNG'
    return im


def pal15(im):
    flat = im.getpalette() or []
    flat = flat + [0] * (768 - len(flat))
    out = []
    for i in range(256):
        r, g, b = flat[i * 3:i * 3 + 3]
        out.append((r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10))
    return out


def tile_words(px, x0, y0, stride_w):
    """px: flat list of indices; returns 8 u32 words for the 8x8 tile at (x0,y0)"""
    words = []
    for y in range(8):
        w = 0
        for x in range(8):
            v = px[(y0 + y) * stride_w + x0 + x] & 15
            w |= v << (4 * x)
        words.append(w)
    return words


def cut_tiles(im, x0, y0, w, h):
    px = list(im.getdata())
    W = im.width
    out = []
    for ty in range(h // 8):
        for tx in range(w // 8):
            out.append(tile_words(px, x0 + tx * 8, y0 + ty * 8, W))
    return out


def fmt_words(name, words, attr='ALIGN4'):
    lines = ['const u32 %s[%d] %s = {' % (name, len(words), attr)]
    for i in range(0, len(words), 8):
        lines.append('    ' + ','.join('0x%08X' % w for w in words[i:i + 8]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def convert(root):
    man = json.load(open(os.path.join(root, 'assets', 'manifest.json')))
    ids = ['/* GENERATED by tools/png2gba.py - do not edit */', '#ifndef GFX_IDS_H', '#define GFX_IDS_H', '']
    c = ['/* GENERATED by tools/png2gba.py - do not edit */', '#include "gba.h"', '']

    # palettes
    env = load(root, man['bg']['env']['png'])
    c.append('const u16 bg_palette[256] ALIGN4 = {')
    p = pal15(env)
    for i in range(0, 256, 16):
        c.append('    ' + ','.join('0x%04X' % v for v in p[i:i + 16]) + ',')
    c.append('};')
    first = load(root, man['sheets'][0]['png'])
    p = pal15(first)
    c.append('const u16 obj_palette[256] ALIGN4 = {')
    for i in range(0, 256, 16):
        c.append('    ' + ','.join('0x%04X' % v for v in p[i:i + 16]) + ',')
    c.append('};')

    def hexpal(lst):
        out = []
        for h in lst:
            h = h.lstrip('#')
            r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
            out.append((r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10))
        return out
    for key, nm in (('lit_warm', 'lit_warm_palette'), ('lit_cool', 'lit_cool_palette'),
                    ('lit_base_warm', 'lit_base_palette')):
        v = hexpal(man[key])
        c.append('const u16 %s[16] = {%s};' % (nm, ','.join('0x%04X' % x for x in v)))
    c.append('')

    # ---- BG charblock 0: environment tiles
    tiles = cut_tiles(env, 0, 0, env.width, env.height)[:man['bg']['env']['count']]
    flat = [w for t in tiles for w in t]
    c.append(fmt_words('env_tiles', flat))
    ids.append('#define ENV_TILE_COUNT %d' % len(tiles))
    anim = load(root, man['bg']['anim']['png'])
    atiles = cut_tiles(anim, 0, 0, anim.width, anim.height)[:man['bg']['anim']['count']]
    c.append(fmt_words('anim_tiles', [w for t in atiles for w in t]))
    ids.append('#define ANIM_GEAR_FRAME_TILES 4')
    ids.append('#define ANIM_CONV_FIRST 16')

    # ---- BG charblock 1: font, minimap area, bigfont, ui, logo
    font = load(root, man['bg']['font']['png'])
    ftiles = cut_tiles(font, 0, 0, font.width, font.height)[:96]
    base = 0
    ids.append('#define CB1_FONT %d' % base)
    base += 96
    ids.append('#define CB1_MINI %d' % base)
    base += 64
    bf = load(root, man['bg']['bigfont']['png'])
    chars = man['bg']['bigfont']['chars']
    bigwords = []
    px = list(bf.getdata())
    for i in range(len(chars)):
        gx, gy = (i % 16) * 16, (i // 16) * 16
        for (ox, oy) in ((0, 0), (8, 0), (0, 8), (8, 8)):
            bigwords.append(tile_words(px, gx + ox, gy + oy, bf.width))
    ids.append('#define CB1_BIG %d' % base)
    ids.append('#define BIG_CHARS "%s"' % chars)
    ids.append('#define BIG_COUNT %d' % len(chars))
    base += len(chars) * 4
    ui = load(root, man['bg']['ui']['png'])
    utiles = cut_tiles(ui, 0, 0, ui.width, ui.height)[:man['bg']['ui']['count']]
    ids.append('#define CB1_UI %d' % base)
    for i, n in enumerate(man['bg']['ui']['names']):
        ids.append('#define UI_%s (CB1_UI + %d)' % (n, i))
    base += len(utiles)
    lg = load(root, man['bg']['logo']['png'])
    lt = cut_tiles(lg, 0, 0, (lg.width // 8) * 8, (lg.height // 8) * 8)
    lw, lh = lg.width // 8, lg.height // 8
    uniq, idx, lmap = [], {}, []
    for t in lt:
        k = tuple(t)
        if k not in idx:
            idx[k] = len(uniq)
            uniq.append(t)
        lmap.append(idx[k])
    ids.append('#define CB1_LOGO %d' % base)
    ids.append('#define LOGO_W %d' % lw)
    ids.append('#define LOGO_H %d' % lh)
    base += len(uniq)
    ids.append('#define CB1_END %d' % base)
    assert base <= 512, 'charblock 1 overflow: %d' % base
    cb1 = [w for t in ftiles for w in t]
    cb1 += [0] * (64 * 8)       # minimap tiles live here (written at run time)
    cb1 += [w for t in bigwords for w in t]
    cb1 += [w for t in utiles for w in t]
    cb1 += [w for t in uniq for w in t]
    c.append(fmt_words('cb1_tiles', cb1))
    c.append('const u16 logo_map[%d] = {%s};' % (len(lmap), ','.join(str(v) for v in lmap)))
    ids.append('#define CB1_TILE_WORDS %d' % len(cb1))

    # ---- OBJ sheets
    objwords = []
    off = 0
    ids.append('')
    for sh in man['sheets']:
        im = load(root, sh['png'])
        px = list(im.getdata())
        fw, fh, cols = sh['fw'], sh['fh'], sh['cols']
        tiles_per = (fw // 8) * (fh // 8)
        ids.append('#define SPR_%s_BASE %d' % (sh['name'].upper(), off))
        for i, name in enumerate(sh['names']):
            gx, gy = (i % cols) * fw, (i // cols) * fh
            for ty in range(fh // 8):
                for tx in range(fw // 8):
                    objwords.append(tile_words(px, gx + tx * 8, gy + ty * 8, im.width))
            ids.append('#define SPR_%s %d' % (name, off + i * tiles_per))
        ids.append('#define SPR_%s_STRIDE %d' % (sh['name'].upper(), tiles_per))
        off += tiles_per * len(sh['names'])
    ids.append('#define OBJ_TILE_COUNT %d' % off)
    assert off <= 1024, 'OBJ VRAM overflow: %d tiles' % off
    c.append(fmt_words('obj_tiles', [w for t in objwords for w in t]))
    ids += ['', '#endif', '']
    with open(os.path.join(root, 'data', 'gfx_data.c'), 'w') as f:
        f.write('\n'.join(c) + '\n')
    with open(os.path.join(root, 'data', 'gfx_ids.h'), 'w') as f:
        f.write('\n'.join(ids))
    print('png2gba: env=%d tiles, cb1=%d tiles, obj=%d tiles' % (len(tiles), base, off))


if __name__ == '__main__':
    convert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
